name: login_button
description: A new widget and its example.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
